# Generated by Django 4.2.16 on 2024-10-24 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentarticleanalysislog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AddField(
            model_name='recruitmentarticle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='monthlymailcount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='mailgenlog',
            name='scout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.scout', verbose_name='スカウト'),
        ),
        migrations.AddField(
            model_name='mailgenlog',
            name='scout_mail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.scoutmail', verbose_name='スカウトメール'),
        ),
        migrations.AddField(
            model_name='mailgenlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='jobpostinganalysislog',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobposting', verbose_name='求人票'),
        ),
        migrations.AddField(
            model_name='jobpostinganalysislog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='idealcandidaterequirement',
            name='ideal_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.idealcandidate', verbose_name='求める人物像'),
        ),
        migrations.AddField(
            model_name='idealcandidatera',
            name='ideal_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.idealcandidate', verbose_name='求める人物像'),
        ),
        migrations.AddField(
            model_name='idealcandidatera',
            name='recruitment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recruitmentarticle', verbose_name='採用記事'),
        ),
        migrations.AddField(
            model_name='idealcandidatejp',
            name='ideal_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.idealcandidate', verbose_name='求める人物像'),
        ),
        migrations.AddField(
            model_name='idealcandidatejp',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobposting', verbose_name='求人票'),
        ),
        migrations.AddField(
            model_name='idealcandidate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='idealcandidate',
            name='job_postings',
            field=models.ManyToManyField(through='base.IdealCandidateJP', to='base.jobposting', verbose_name='求人票'),
        ),
        migrations.AddField(
            model_name='idealcandidate',
            name='recruitment_articles',
            field=models.ManyToManyField(through='base.IdealCandidateRA', to='base.recruitmentarticle', verbose_name='採用記事'),
        ),
        migrations.AddField(
            model_name='idealcandidate',
            name='work_value_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dc_work_value_1', to='base.workvalue', verbose_name='仕事観1'),
        ),
        migrations.AddField(
            model_name='idealcandidate',
            name='work_value_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dc_work_value_2', to='base.workvalue', verbose_name='仕事観2'),
        ),
        migrations.AddField(
            model_name='idealcandidate',
            name='work_value_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dc_work_value_3', to='base.workvalue', verbose_name='仕事観3'),
        ),
        migrations.AddField(
            model_name='historicalworkvalue',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscoutsender',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='historicalscoutsender',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='job_posting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.jobposting', verbose_name='求人票'),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='recruitment_article_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.recruitmentarticle', verbose_name='採用記事1'),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='recruitment_article_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.recruitmentarticle', verbose_name='採用記事2'),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='recruitment_article_3',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.recruitmentarticle', verbose_name='採用記事3'),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='scout',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.scout', verbose_name='スカウト'),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='scout_sender',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.scoutsender', verbose_name='スカウト送信者'),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='strength_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.companystrength', verbose_name='強み1'),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='strength_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.companystrength', verbose_name='強み2'),
        ),
        migrations.AddField(
            model_name='historicalscoutmail',
            name='strength_3',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.companystrength', verbose_name='強み3'),
        ),
        migrations.AddField(
            model_name='historicalscout',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='historicalscout',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscout',
            name='ideal_candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.idealcandidate', verbose_name='求める人物像'),
        ),
        migrations.AddField(
            model_name='historicalrecruitmentarticleanalysislog',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrecruitmentarticleanalysislog',
            name='recruitment_article',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.recruitmentarticle', verbose_name='採用記事'),
        ),
        migrations.AddField(
            model_name='historicalrecruitmentarticleanalysislog',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AddField(
            model_name='historicalrecruitmentarticle',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='historicalrecruitmentarticle',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmonthlymailcount',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='historicalmonthlymailcount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmailgenlog',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmailgenlog',
            name='scout',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.scout', verbose_name='スカウト'),
        ),
        migrations.AddField(
            model_name='historicalmailgenlog',
            name='scout_mail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.scoutmail', verbose_name='スカウトメール'),
        ),
        migrations.AddField(
            model_name='historicalmailgenlog',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='historicallabel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalkpi',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='historicalkpi',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobpostinganalysislog',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobpostinganalysislog',
            name='job_posting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.jobposting', verbose_name='求人票'),
        ),
        migrations.AddField(
            model_name='historicaljobpostinganalysislog',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AddField(
            model_name='historicaljobposting',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='historicaljobposting',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalidealcandidaterequirement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalidealcandidaterequirement',
            name='ideal_candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.idealcandidate', verbose_name='求める人物像'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidatera',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalidealcandidatera',
            name='ideal_candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.idealcandidate', verbose_name='求める人物像'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidatera',
            name='recruitment_article',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.recruitmentarticle', verbose_name='採用記事'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidatejp',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalidealcandidatejp',
            name='ideal_candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.idealcandidate', verbose_name='求める人物像'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidatejp',
            name='job_posting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.jobposting', verbose_name='求人票'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidate',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalidealcandidate',
            name='work_value_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.workvalue', verbose_name='仕事観1'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidate',
            name='work_value_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.workvalue', verbose_name='仕事観2'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidate',
            name='work_value_3',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.workvalue', verbose_name='仕事観3'),
        ),
        migrations.AddField(
            model_name='historicalcompanystrengthra',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompanystrengthra',
            name='recruitment_article',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.recruitmentarticle', verbose_name='採用記事'),
        ),
        migrations.AddField(
            model_name='historicalcompanystrengthra',
            name='strength',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.companystrength', verbose_name='企業の強み'),
        ),
        migrations.AddField(
            model_name='historicalcompanystrengthjp',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompanystrengthjp',
            name='job_posting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.jobposting', verbose_name='求人票'),
        ),
        migrations.AddField(
            model_name='historicalcompanystrengthjp',
            name='strength',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.companystrength', verbose_name='企業の強み'),
        ),
        migrations.AddField(
            model_name='historicalcompanystrength',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='historicalcompanystrength',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompanymedia',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='historicalcompanymedia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompanyinfo',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業ID'),
        ),
        migrations.AddField(
            model_name='historicalcompanyinfo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidateworkhistory',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='historicalcandidateworkhistory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidateskill',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='historicalcandidateskill',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidatepreferredoccupation',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='historicalcandidatepreferredoccupation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidatepreferredlocation',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='historicalcandidatepreferredlocation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidatepreferredindustry',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='historicalcandidatepreferredindustry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidatelabel',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='historicalcandidatelabel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidatelabel',
            name='label',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.label', verbose_name='ラベル'),
        ),
        migrations.AddField(
            model_name='historicalcandidatefeeling',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidatecertification',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='historicalcandidatecertification',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidateacademichistory',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='historicalcandidateacademichistory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='anxiety_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidatefeeling', verbose_name='転職に対する不安1'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='anxiety_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidatefeeling', verbose_name='転職に対する不安2'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='dissatisfaction_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidatefeeling', verbose_name='現職に対する不満1'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='dissatisfaction_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidatefeeling', verbose_name='現職に対する不満2'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='expectation_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidatefeeling', verbose_name='転職に対する期待1'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='expectation_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.candidatefeeling', verbose_name='転職に対する期待2'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='work_value_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.workvalue', verbose_name='仕事観1'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='work_value_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.workvalue', verbose_name='仕事観2'),
        ),
        migrations.AddField(
            model_name='companystrengthra',
            name='recruitment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recruitmentarticle', verbose_name='採用記事'),
        ),
        migrations.AddField(
            model_name='companystrengthra',
            name='strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.companystrength', verbose_name='企業の強み'),
        ),
        migrations.AddField(
            model_name='companystrengthjp',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobposting', verbose_name='求人票'),
        ),
        migrations.AddField(
            model_name='companystrengthjp',
            name='strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.companystrength', verbose_name='企業の強み'),
        ),
        migrations.AddField(
            model_name='companystrength',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='companystrength',
            name='job_postings',
            field=models.ManyToManyField(through='base.CompanyStrengthJP', to='base.jobposting', verbose_name='求人票'),
        ),
        migrations.AddField(
            model_name='companystrength',
            name='recruitment_articles',
            field=models.ManyToManyField(through='base.CompanyStrengthRA', to='base.recruitmentarticle', verbose_name='採用記事'),
        ),
        migrations.AddField(
            model_name='companymedia',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='企業ID'),
        ),
        migrations.AddField(
            model_name='candidateworkhistory',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='candidatepreferredoccupation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='candidatepreferredlocation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='candidatepreferredindustry',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='candidatelabel',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='candidatelabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.label', verbose_name='ラベル'),
        ),
        migrations.AddField(
            model_name='candidatecertification',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='candidateacademichistory',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidate', verbose_name='候補者'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='anxiety_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anxiety_1', to='base.candidatefeeling', verbose_name='転職に対する不安1'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='anxiety_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anxiety_2', to='base.candidatefeeling', verbose_name='転職に対する不安2'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dissatisfaction_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dissatisfaction_1', to='base.candidatefeeling', verbose_name='現職に対する不満1'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dissatisfaction_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dissatisfaction_2', to='base.candidatefeeling', verbose_name='現職に対する不満2'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expectation_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expectation_1', to='base.candidatefeeling', verbose_name='転職に対する期待1'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expectation_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expectation_2', to='base.candidatefeeling', verbose_name='転職に対する期待2'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='labels',
            field=models.ManyToManyField(through='base.CandidateLabel', to='base.label', verbose_name='ラベル'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_value_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_work_value_1', to='base.workvalue', verbose_name='仕事観1'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_value_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_work_value_2', to='base.workvalue', verbose_name='仕事観2'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentarticle',
            constraint=models.UniqueConstraint(fields=('company', 'url'), name='company_url_ra'),
        ),
        migrations.AddConstraint(
            model_name='kpi',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='company_year_month'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('company', 'url'), name='company_url_jp'),
        ),
        migrations.AddConstraint(
            model_name='companymedia',
            constraint=models.UniqueConstraint(fields=('company', 'media'), name='company_media'),
        ),
        migrations.AddConstraint(
            model_name='candidatepreferredoccupation',
            constraint=models.UniqueConstraint(fields=('candidate', 'occupation'), name='candidate_occupation'),
        ),
        migrations.AddConstraint(
            model_name='candidatepreferredlocation',
            constraint=models.UniqueConstraint(fields=('candidate', 'location'), name='candidate_location'),
        ),
        migrations.AddConstraint(
            model_name='candidatepreferredindustry',
            constraint=models.UniqueConstraint(fields=('candidate', 'industry'), name='candidate_industry'),
        ),
    ]
