# Generated by Django 4.2.16 on 2024-09-10 08:41

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def add_initial_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:  # noqa: ARG001
    """
    マイグレーション時に初期データを追加する。
    """
    # マイグレーション時に使用するモデルを取得
    Company = apps.get_model("base", "Company")

    # データを追加
    Company.objects.create(name="運営会社")


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [  # noqa: RUF012
        ("base", "0002_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.RunPython(add_initial_data),
    ]
