# Generated by Django 4.2.16 on 2024-10-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_add_initial_data_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystrengthjp',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'ある程度関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AddField(
            model_name='companystrengthra',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'ある程度関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AddField(
            model_name='historicalcompanystrengthjp',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'ある程度関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AddField(
            model_name='historicalcompanystrengthra',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'ある程度関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidatejp',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'ある程度関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AddField(
            model_name='historicalidealcandidatera',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'ある程度関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AddField(
            model_name='idealcandidatejp',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'ある程度関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AddField(
            model_name='idealcandidatera',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'ある程度関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
    ]
