# Generated by Django 4.2.16 on 2024-11-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_companystrengthjp_relevance_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id_in_media',
            field=models.CharField(default='', max_length=255, verbose_name='採用媒体内ID'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='capital',
            field=models.IntegerField(blank=True, null=True, verbose_name='資本金(千円)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='revenue',
            field=models.IntegerField(blank=True, null=True, verbose_name='売上高(百万円)'),
        ),
        migrations.AlterField(
            model_name='companymedia',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], verbose_name='採用媒体'),
        ),
        migrations.AlterField(
            model_name='companystrengthjp',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'やや関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AlterField(
            model_name='companystrengthra',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'やや関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='id_in_media',
            field=models.CharField(default='', max_length=255, verbose_name='採用媒体内ID'),
        ),
        migrations.AlterField(
            model_name='historicalcompanyinfo',
            name='capital',
            field=models.IntegerField(blank=True, null=True, verbose_name='資本金(千円)'),
        ),
        migrations.AlterField(
            model_name='historicalcompanyinfo',
            name='revenue',
            field=models.IntegerField(blank=True, null=True, verbose_name='売上高(百万円)'),
        ),
        migrations.AlterField(
            model_name='historicalcompanymedia',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], verbose_name='採用媒体'),
        ),
        migrations.AlterField(
            model_name='historicalcompanystrengthjp',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'やや関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AlterField(
            model_name='historicalcompanystrengthra',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'やや関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AlterField(
            model_name='historicalidealcandidatejp',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'やや関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AlterField(
            model_name='historicalidealcandidatera',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'やや関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AlterField(
            model_name='historicaljobposting',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], verbose_name='採用媒体'),
        ),
        migrations.AlterField(
            model_name='historicalrecruitmentarticle',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], verbose_name='採用媒体'),
        ),
        migrations.AlterField(
            model_name='historicalscout',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], verbose_name='採用媒体'),
        ),
        migrations.AlterField(
            model_name='idealcandidatejp',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'やや関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AlterField(
            model_name='idealcandidatera',
            name='relevance_level',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'とても関連している'), (4, 'やや関連している'), (3, 'どちらともいえない'), (2, 'あまり関連していない'), (1, '全く関連していない')], null=True, verbose_name='関連度'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], verbose_name='採用媒体'),
        ),
        migrations.AlterField(
            model_name='recruitmentarticle',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], verbose_name='採用媒体'),
        ),
        migrations.AlterField(
            model_name='scout',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], verbose_name='採用媒体'),
        ),
    ]
