# Generated by Django 4.2.16 on 2024-11-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_candidate_id_in_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscout',
            name='media',
        ),
        migrations.RemoveField(
            model_name='scout',
            name='media',
        ),
        migrations.AddField(
            model_name='candidate',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], default=1, verbose_name='採用媒体'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='media',
            field=models.SmallIntegerField(choices=[(1, 'BIZREACH'), (2, 'dodaダイレクト'), (3, 'Green'), (4, 'Wantedly'), (5, 'リクルート ダイレクトスカウト'), (6, 'マイナビ転職'), (7, 'エン転職ダイレクト'), (8, 'AMBI'), (9, 'Linkedin'), (10, 'paiza'), (11, 'OpenWork'), (12, 'HRMOS'), (13, 'Nishika'), (14, 'レバテックダイレクト'), (98, '自社メディア'), (99, 'その他')], default=1, verbose_name='採用媒体'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateworkhistory',
            name='experience',
            field=models.TextField(blank=True, default='', verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='historicalcandidateworkhistory',
            name='experience',
            field=models.TextField(blank=True, default='', verbose_name='概要'),
        ),
    ]
