# Generated by Django 4.2.16 on 2024-11-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_historicalscout_media_remove_scout_media_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': '<< 候補者 >>', 'verbose_name_plural': '<< 候補者 >>'},
        ),
        migrations.AlterModelOptions(
            name='historicalcandidate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical << 候補者 >>', 'verbose_name_plural': 'historical << 候補者 >>'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='company_candidate_id',
        ),
        migrations.RemoveField(
            model_name='historicalcandidate',
            name='company_candidate_id',
        ),
        migrations.AlterField(
            model_name='historicalscoutmail',
            name='scout_sender',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.scoutsender', verbose_name='差出人'),
        ),
        migrations.AlterField(
            model_name='scoutmail',
            name='scout_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.scoutsender', verbose_name='差出人'),
        ),
    ]
